plugin: aws_ec2

aws_access_key: AKIASB5WP6AORPOOLKVG
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
